name: gitleaks
on: [push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    container:
      image: docker:25-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run gitleaks
        run: |
          docker-compose up -d gitleaks |
          docker-compose logs -f gitleaks
